apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-operators

resources:
  - servicemesh-namespace.yaml
  - servicemesh-subscription.yaml
  - servicemesh-controlplane.yaml
  - servicemesh-memberroll.yaml
